### ISSUE TITLE
Please clarify the difference with Add delimited text

### ISSUE THREAD

**Issue by pcav** [klausib/xyToPoint#4]
The functionality of this plugin seems very similar to the existing core plugin.
Please explain why this new one is necessary.
Thanks.

**Comment by klausib** [comment]
As far as I know, the core Plugin only works with tables in a  filesystem. I’m not an intense QGIS user, so this is the information I got from the user inside my Organisation. There was the need to create Point Layers from connected Database tables. But if it is not like that, I will remove the Plugin – because there would be no use for it, of course.

Regards
Nikolaus

Von: Paolo Cavallini [mailto:notifications@github.com]
Gesendet: Dienstag, 10. März 2015 10:59
An: klausib/xyToPoint
Betreff: [xyToPoint] Please clarify the difference with Add delimited text (#4)


The functionality of this plugin seems very similar to the existing core plugin.
Please explain why this new one is necessary.
Thanks.

**Comment by pcav** [comment]
Thanks for the explanation, it makes sense. Please check also RT Qspider.
I think adding a similar note to the About would be very good for users to understand when it is better using this plugin.

**Comment by klausib** [comment]
Yes, you’re right.

mit freundlichen Grüßen
Nikolaus Batlogg





Nikolaus Batlogg
Abteilung Geoinformation
Landesamt für Vermessung und Geoinformation
Johannitergasse 6
6800 Feldkirch
T: +43(0)5522/75482-60220
F: +43(0)5522/75482-6
E: nikolaus.batlogg@vorarlberg.at<mailto:nikolaus.batlogg@vorarlberg.at>
I: http://www.vorarlberg.at/lvg
Rechtsverbindlichen Schriftverkehr
(zB Anträge, Rechtsmittel) richten Sie an:
F: +43(0)5522/75482-6
E: landesvermessungsamt@vorarlberg.at<mailto:landesvermessungsamt@vorarlberg.at>

Von: Paolo Cavallini [mailto:notifications@github.com]
Gesendet: Dienstag, 10. März 2015 11:07
An: klausib/xyToPoint
Cc: Batlogg Nikolaus
Betreff: Re: [xyToPoint] Please clarify the difference with Add delimited text (#4)


Thanks for the explanation, it makes sense. Please check also RT Qspider.
I think adding a similar note to the About would be very good for users to understand when it is better using this plugin.

**Comment by klausib** [comment]
Note added.
